version: '2.0'
services:
  spotibridge:
    image: alpha200/spotibridge
    container_name: spotibridge
    environment:
      SPOTIFY_USERNAME: ''
      SPOTIFY_CLIENT_ID: ''
      SPOTIFY_CLIENT_SECRET: ''
      SPOTIFY_REDIRECT_URI: ''
      MQTT_HOST: "192.168.1.1"
      MQTT_USER: ""
      MQTT_PASSWORD: ""
    volumes:
      - './.cache-username:/usr/src/app/.cache-username'
